import { CommonTemplateProps } from '../interface/index'

// Template for producing React component with prop selectable SVG version OUTLINE/FILLED
function componentCommonTemplate ({ fileName, filled, outlined }:CommonTemplateProps) {
  const render = `
// GENERATED BY ./scripts/iconScript.ts

import * as React from 'react';
import { IconCommonProps, valuesMap } from '../helper';
import { flipFunction } from '../flipFunction';

function EOS_${fileName}({size = "m", color = "black", rotate = 0, horizontalFlip = false, verticalFlip = false, theme = "outlined"}: IconCommonProps) {
    const sizeString: string = size.toString()
    if(Object.keys(valuesMap).includes(sizeString)) {
        size = valuesMap[size]
    }
    const { scaleX, scaleY, translateX, translateY } = flipFunction({horizontalFlip,verticalFlip})
return (
    <>
    {
        (theme === "filled") &&
        // Filled version
        ${filled}
    }
    {
        (theme === "outlined") &&
        // Outlined version
        ${outlined}
    }
    </>
    );
};

export default EOS_${fileName};
`
  return (render)
}

export default componentCommonTemplate
