import { TemplateProps } from '../interface/index';

function componentTemplate ({fileName,data}:TemplateProps) {
    const render = `
// GENERATED BY ./scripts/iconScript.ts

import * as React from 'react';
import { IconProps, ValueMap } from '../helper';

function Eos${fileName}({size = "m", color = "black", rotate = 0}: IconProps) {
    const valuesMap: ValueMap = {
        xs: 4,
        s: 8,
        base: 14,
        m: 18,
        l: 24,
        xl: 32,
        xxl: 48,
        xxxl: 64,
    }
    const sizeString: string = size.toString()
 
    if(Object.keys(valuesMap).includes(sizeString)) {
        size = valuesMap[size]
    }
return (
    ${data}
    );
};

export default Eos${fileName};
`;
    return (render)
}

export default componentTemplate;