interface TemplateProps {
    fileName: string;
    data: string;
}

function componentTemplate ({fileName,data}:TemplateProps) {
    const render = `
// GENERATED BY ./scripts/iconScript.ts

import * as React from 'react';
import { IconProps } from '../helper';

function Eos${fileName}({size = 36, color = "black", rotate = 0}: IconProps) {
return (
    ${data}
    );
};


export default Eos${fileName};
`;
    return (render)
}

export default componentTemplate;