import { StoryBookProps } from '../interface/index'

function storybookTemplate ({ fileName, outlined, filled }:StoryBookProps) {
  let importStatement = ''
  let stories = ''
  if (filled === '' && outlined === '') {
    importStatement = ''
    stories = ''
  } else if (filled !== '' && outlined === '') {
    importStatement = `import { EOS_${filled} } from '../../src/icon/'`
    stories = `export const Filled: ComponentStory<typeof EOS_${filled}> = (args) => <EOS_${filled} {...args} />
    Filled.parameters = { controls: { exclude: ['theme'] } }`
  } else if (filled === '' && outlined !== '') {
    importStatement = `import { EOS_${outlined} } from '../../src/icon/'`
    stories = `export const Outlined: ComponentStory<typeof EOS_${outlined}> = (args) => <EOS_${outlined} {...args} />
    Outlined.parameters = { controls: { exclude: ['theme'] } }`
  } else {
    importStatement = `import { EOS_${outlined} } from '../../src/icon/'
    import { EOS_${filled} } from '../../src/icon/'`
    stories = `export const Filled: ComponentStory<typeof EOS_${filled}> = (args) => <EOS_${filled} {...args} />
    Filled.parameters = { controls: { exclude: ['theme'] } }
    export const Outlined: ComponentStory<typeof EOS_${outlined}> = (args) => <EOS_${outlined} {...args} />
    Outlined.parameters = { controls: { exclude: ['theme'] } }`
  }

  const render = `
    // GENERATED BY ./scripts/storyBookScript.ts
    import React from 'react'
    import { ComponentStory, ComponentMeta } from '@storybook/react'
    
    import { EOS_${fileName} } from '../../src/icon/'
    ${importStatement}
    
    export default {
      title: 'icon/EOS_${fileName}',
      component: EOS_${fileName},
      argTypes: {
        color: { control: 'color' },
        rotate: { control: 'number' },
        size: {
          options: ['xs','s','base','m','l','xl','xxl','xxxl'],
          control: {type: 'radio'}
        }
      }
    } as ComponentMeta<typeof EOS_${fileName}>
    
    export const Default: ComponentStory<typeof EOS_${fileName}> = (args) => <EOS_${fileName} {...args} />

    ${stories}
    `
  return (render)
}

export default storybookTemplate
