version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "vinayaksh42"
      - "EOS-uiux-Solutions/mentors"
    allow:
      - dependency-name: "eos-icons"
    labels:
      - "npm"
      - "dependencies"
