version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "live"
    reviewers:
      - "vinayaksh42"
      - "EOS-uiux-Solutions/mentors"
    allowed_updates:
      - match:
          dependency_name: "eos-icons"
    commit_message:
      prefix: "fix"
      include_scope: true
      - match:
          dependency_name: "eos-icons"
