name: Cache Node Modules
on:
  pull_request:
  push:
    branches: [ main ]
jobs:
  cache_node_modules:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@main
      - uses: actions/setup-node@main
        with:
          node-version: '14'
      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@main
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('package-lock.json') }}
        
      - name: Install dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm install