name: Release
on:
  push:
    branches: [ main ]
jobs:
  release:
    name: Release
    needs: cache_node_modules
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@main

      - name: Load node_modules
        id: cache-node-modules
        uses: actions/cache@main
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('package-lock.json') }}

      - name: Install node_modules
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm install
      - run: npm run generate
      - run: npm run test
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}