name: Test
on:
  pull_request:
  push:
    branches: [ main ]
jobs:
  release:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v2

      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node_modules-deploy-${{ hashFiles('package-lock.json') }}

      - name: Install node modules
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm install

      - run: npm run generate
      - run: npm run test